version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5436:5432"
    environment:
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_DATABASE=shortenedlinks

  redis:
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=docker
    volumes:
      - redis_data:/bitnami/redis/data

volumes:
  redis_data: