POST http://localhost:3333/api/links
Content-Type: application/json

{
    "code": "querotela",
    "url": "https://quero-tela-frontend.vercel.app/"
}

###

GET http://localhost:3333/api/links

###

GET http://localhost:3333/querotela