POST http://localhost:3333/api/links
Content-Type: application/json

{
    "code": "wiki",
    "url": "https://www.wikipedia.org/"
}

###

GET http://localhost:3333/api/links

###

GET http://localhost:3333/github

###

GET http://localhost:3333/api/metrics